name: Create a comment on new issues

on: 
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github text"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash